sudo: required

services: docker

before_install:
  - docker-compose build

script:
  - docker-compose run --rm app sh -c 'python manage.py test'
  - docker-compose run --rm next sh -c 'npm run test'
